[versions]
axCore = "1.8.0"
axAppcompat = "1.4.2"
axConstraintlayout = "2.1.4"
axNavigation = "2.4.2"
googleMaterial = "1.7.0-alpha02"
androidApplication = "7.4.0-alpha05"
androidLibrary = "7.4.0-alpha05"
hilt = "2.42"
kotlin = "1.6.21"
room = "2.4.2"
spotless = "6.7.2"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "axCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "axAppcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "axConstraintlayout" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "axNavigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "axNavigation" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

google-material = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
google-dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

square-leakcanary = "com.squareup.leakcanary:leakcanary-android:2.9.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplication" }
android-library = { id = "com.android.library", version.ref = "androidLibrary" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "axNavigation" }
