[versions]
axCore = "1.8.0"
axAppcompat = "1.4.2"
axConstraintlayout = "2.1.4"
axNavigation = "2.5.0"
googleMaterial = "1.7.0-alpha03"
androidApplication = "7.4.0-alpha08"
androidLibrary = "7.4.0-alpha09"
hilt = "2.43"
ktor = "2.0.3"
lifecycle = "2.5.0"
kotlin = "1.7.10"
room = "2.5.0-alpha02"
spotless = "6.8.0"

[libraries]
arrow-core = "io.arrow-kt:arrow-core:1.1.2"

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "axCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "axAppcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "axConstraintlayout" }
androidx-swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"

androidx-lifecycle-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "axNavigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "axNavigation" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

google-material = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
google-dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
qbittorrent-client = "org.drewcarlson:qbittorrent-client:0.6.2"
square-leakcanary = "com.squareup.leakcanary:leakcanary-android:2.9.1"

testing-junit = "junit:junit:4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplication" }
android-library = { id = "com.android.library", version.ref = "androidLibrary" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "axNavigation" }
